// <auto-generated />
using System;
using FraudRiskMgmt.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FraudRiskMgmt.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260907063927_AddInvestigationWorkflow")]
    partial class AddInvestigationWorkflow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FraudRiskMgmt.API.Models.Alert", b =>
                {
                    b.Property<int>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlertId"));

                    b.Property<int?>("AssignedTo")
                        .HasColumnType("int");

                    b.Property<int?>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RiskScore")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("AlertId");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("CaseId");

                    b.HasIndex("TransactionId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("FraudRiskMgmt.API.Models.CaseActionProposal", b =>
                {
                    b.Property<int>("CaseActionProposalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaseActionProposalId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DecidedBy")
                        .HasColumnType("int");

                    b.Property<string>("DecisionNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProposedBy")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CaseActionProposalId");

                    b.HasIndex("CaseId");

                    b.HasIndex("DecidedBy");

                    b.HasIndex("ProposedBy");

                    b.ToTable("CaseActionProposals");
                });

            modelBuilder.Entity("FraudRiskMgmt.API.Models.Cases", b =>
                {
                    b.Property<int>("CaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaseId"));

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OpenedBy")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CaseId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OpenedBy");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("FraudRiskMgmt.API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("FraudRiskMgmt.API.Models.InvestigationNote", b =>
                {
                    b.Property<int>("InvestigationNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvestigationNoteId"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("InvestigationNoteId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CaseId");

                    b.ToTable("InvestigationNotes");
                });

            modelBuilder.Entity("FraudRiskMgmt.API.Models.Transactions", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameDest")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOrig")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("NewBalanceDest")
                        .HasColumnType("float");

                    b.Property<double>("NewBalanceOrig")
                        .HasColumnType("float");

                    b.Property<double>("OldBalanceDest")
                        .HasColumnType("float");

                    b.Property<double>("OldBalanceOrg")
                        .HasColumnType("float");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RiskScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("TransactionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FraudRiskMgmt.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FraudRiskMgmt.API.Models.Alert", b =>
                {
                    b.HasOne("FraudRiskMgmt.API.Models.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedTo");

                    b.HasOne("FraudRiskMgmt.API.Models.Cases", "Case")
                        .WithMany("Alerts")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FraudRiskMgmt.API.Models.Transactions", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedToUser");

                    b.Navigation("Case");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("FraudRiskMgmt.API.Models.CaseActionProposal", b =>
                {
                    b.HasOne("FraudRiskMgmt.API.Models.Cases", "Case")
                        .WithMany("ActionProposals")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FraudRiskMgmt.API.Models.User", "DecidedByUser")
                        .WithMany()
                        .HasForeignKey("DecidedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FraudRiskMgmt.API.Models.User", "ProposedByUser")
                        .WithMany()
                        .HasForeignKey("ProposedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("DecidedByUser");

                    b.Navigation("ProposedByUser");
                });

            modelBuilder.Entity("FraudRiskMgmt.API.Models.Cases", b =>
                {
                    b.HasOne("FraudRiskMgmt.API.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FraudRiskMgmt.API.Models.User", "OpenedByUser")
                        .WithMany()
                        .HasForeignKey("OpenedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("OpenedByUser");
                });

            modelBuilder.Entity("FraudRiskMgmt.API.Models.InvestigationNote", b =>
                {
                    b.HasOne("FraudRiskMgmt.API.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FraudRiskMgmt.API.Models.Cases", "Case")
                        .WithMany("InvestigationNotes")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("FraudRiskMgmt.API.Models.Transactions", b =>
                {
                    b.HasOne("FraudRiskMgmt.API.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FraudRiskMgmt.API.Models.Cases", b =>
                {
                    b.Navigation("ActionProposals");

                    b.Navigation("Alerts");

                    b.Navigation("InvestigationNotes");
                });
#pragma warning restore 612, 618
        }
    }
}
